name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Switch to Nightly
      run: rustup default nightly
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Format
      run: cargo fmt --check
      working-directory: ./sample

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Switch to Nightly
      run: rustup default nightly
    - name: Install clippy
      run: rustup component add clippy
    - name: Clippy
      run: cargo clippy
      working-directory: ./sample

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Switch to Nightly
      run: rustup default nightly
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Build main
      run: wasm-pack build --target web
      working-directory: ./sample/src/main
    - name: Build worker
      run: wasm-pack build --target web
      working-directory: ./sample/src/worker
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install Node packages
      run: npm i
      working-directory: ./sample
    - name: Build site
      run: npm run build
      working-directory: ./sample
    - uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './sample/dist/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
